language: node_js
node_js: stable
os: osx
addons:
  ssh_known_hosts: 60.205.191.214
before_install:
- openssl aes-256-cbc -K $encrypted_b9005e32c66a_key -iv $encrypted_b9005e32c66a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success:
- ssh root@60.205.191.214 "cd /var/images/index/;git pull ;pm2 delete nuxt;npm run build;pm2 start npm --name nuxt -- start"

notifications:
  email:
    recipients:
      - thinkxzx@foxmail.com
    on_success: never # default: change
    on_failure: always # default: always